# Generated by Django 5.2.8 on 2025-12-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_agentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_applications/license_documents/'),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='nid_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_applications/nid_documents/'),
        ),
    ]
